# Generated by Django 5.1.4 on 2025-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DgaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='message',
        ),
        migrations.RemoveField(
            model_name='data',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='booleano',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='caudal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
