# Generated by Django 5.1.4 on 2025-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DgaApp', '0002_remove_data_message_remove_data_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='booleano',
        ),
        migrations.RemoveField(
            model_name='data',
            name='caudal',
        ),
        migrations.RemoveField(
            model_name='data',
            name='fecha',
        ),
        migrations.AddField(
            model_name='data',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
